name: Build Plugins

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    if: ${{ github.repository != 'Artemis-RGB/Artemis.PluginTemplate' && '[ -f .template ]' }}
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Set version to env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Update plugin.json version
        uses: jossef/action-set-json-field@v2.2
        with:
          file: src/Artemis.Plugins.ChromaSdkHacks/plugin.json
          field: Version
          value: ${{ env.RELEASE_VERSION }}

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update version ${{ env.RELEASE_VERSION }}"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ github.token }}
          tags: true

      - name: Build Plugins
        run: dotnet publish -c Release src

      - name: Install Plugin Uploader
        run: dotnet tool install ArtemisRGB.Tools.PluginUploader --global

      - name: Upload to workshop
        run: artemis-plugin-uploader upload-all --pat ${{ secrets.WORKSHOP_PAT }} --folder src
